name: 'Three Columns'
multiple: FALSE
category: 'Projects'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--projects
        filters:
          - fields[node--projects]=drupal_internal__nid,path,title,field_project_category,field_project_coordinator,field_project_deadline,field_project_name,body
          - fields[taxonomy_term--field_project_category]=tid,name,term_2_slug
          - include=field_project_category
          - filter[status][value]=1
          - page[offset]=0
          - page[limit]=3
  link:
    type: url_extended
    label: 'Lien'
